### ISSUE TITLE
Add Slice Tool

### ISSUE THREAD

**Issue by tbock** [USEPA/R9-CentralBasin#1]
Looks like it just slices everything

**Comment by tbock** [comment]
Also can add ability to ignore layers? https://esridevsummit.github.io/2021-3D-jsapi/client-side-3d-analysis.html#/7

**Comment by bsnider** [comment]
this is already part of the widget, no?

**Comment by tbock** [comment]
Yes it does appear to be. I think the main issue I was having was just the ability to turn the slice tool on/off.

**Comment by tbock** [comment]
Done.
