### ISSUE TITLE
Create translation script (tomato vs tomato) between WRD and GAMA

### ISSUE THREAD

**Issue by tbock** [USEPA/R9-CentralBasin#100]
Gama calls analytes one thing and WRD calls them another.  The crosswalk should be complete or nearly complete and we need a script to translate the data.   See tab VOTE HERE-MatchedChemicals.

**Comment by tbock** [comment]
@abbyrrobles so we are just going to use GAMA now I hear? so no need for this?

**Comment by abbyrrobles** [comment]
Sounds like it. I can close.
