### ISSUE TITLE
Revised 710 Study Area

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#24]
Brian will be sending you a new file which will include the existing 710 area but also include more area to the immediate east of the 710 area. Can you provide that as an additional layers. Note, we will be using this polygon as a test area for inclusion of monitoring wells from the Water board. We are hoping to get a data set that includes just monitoring wells for sites that exclues the monitoring wells associated with gas stations. The 710 area along with the Waymire Drum site are the “cage” candidates.

**Comment by tbock** [comment]
@GeoFe33 @froberts status?

**Comment by GeoFe33** [comment]
Completed.
![image](https://user-images.githubusercontent.com/54416878/191808665-d58d4c33-1a62-4ada-8991-a110cad7581a.png)
