### ISSUE TITLE
Review Wells 3d dataset

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#25]
It seems that those in yellow are not present in this data set. It is likely that they only pertain to the adjacent West Coast basin. Can you confirm that they are without data, and if so confirm with us. I think we will leave them as placeholders in the event that the State or WRD wants to include them – possibly if we include the West Coast basin (which is under WRD jurisdiction)
The layers in blue appear to be identical. Lets get rid of one and name that layer: Change Monitoring Wells (or MW) to 'Nested Monitoring Wells' per the revised attribute table (attached also)

**Comment by GeoFe33** [comment]
More details here:
[Fwd_ Notes on the 3d for Frank.pdf](https://github.com/USEPA/R9-CentralBasin/files/8641388/Fwd_.Notes.on.the.3d.for.Frank.pdf)

**Comment by tbock** [comment]
@GeoFe33 status?

**Comment by GeoFe33** [comment]
All Wells 2D and 3D are present.
![image](https://user-images.githubusercontent.com/54416878/191807301-07064d97-e4bb-4e36-a31f-683e1ca78cad.png)

Need layer links for the layers referenced in this issue.

**Comment by tbock** [comment]
@kplank1 can we close this? What is the status otherwise?

**Comment by kplank1** [comment]
Following up with Matt on this issue

**Comment by kplank1** [comment]
No email back from Matt regarding the dual nested-wells
