### ISSUE TITLE
Search Box Over Post

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#27]
Search Box Overfor WRD number disappears when you click on the search box above. (it is over posted by above box).. Also, are search boxes very difficult to add.  Ideally we would have one for the STATE SOUR(CE) NUMBER and the COMMON NAME.

**Comment by tbock** [comment]
Not following first part about disappearing.  Maybe that is resolved. 

For the second part what you are describing is a filter really.  At a minimum would probably be good to have these inputs be autocompletes.

**Comment by kplank1** [comment]
No WRD layers anymore, included filters.
