### ISSUE TITLE
Above view to below ground zoom

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#28]
Can we incorporate the zoom to option so we can easily move from subsurface well location to above surface well loacation? In other words moving from the subsurface locations below to the above surface location below. As it is you need to re calibrate moving from one to the other. We noticed that the zoom function helps, but perhaps there is a neater way to do it?

**Comment by kplank1** [comment]
Not necessary anymore, only showing 3D wells presently.
