### ISSUE TITLE
Add ability to query by value

### ISSUE THREAD

**Issue by tbock** [USEPA/R9-CentralBasin#3]
@froberts what layers are we talking about here? 
You mentioned "TCE gt X" any more details?

**Comment by froberts** [comment]
@tbock I think the above would be cool for the 2D features.  However, the issue we run into is in 3D we have wells that are sampled multiple times, so we have multiple colors/shading occurring on top of one another.  Our workaround currently is I change the buffer diameter, so the hottest value has the biggest buffer, so it appears on top.  If we could color and buffer on the fly, that might be a way to do this.  So it all comes down to if we can control when the features are drawn when they overlap.
