### ISSUE TITLE
Edit Attribute Order in Popups

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#34]
Order attributes and set up as specified with aliases as identified in Excel sent by Matt

**Comment by froberts** [comment]
[Attribute_Order.xlsx](https://github.com/USEPA/R9-CentralBasin/files/6388386/Attribute_Order.xlsx)
See attributes in this excel sheet

**Comment by tbock** [comment]
@GeoFe33 status?

**Comment by GeoFe33** [comment]
Not complete.

**Comment by GeoFe33** [comment]
Updated pop-ups for Monitoring Wells 2D and 3D.  Still need to do the same for other types.  Also, domains need to be established to define coded values.

**Comment by abbyrrobles** [comment]
Updated and configured popup lists on all wells.

**Comment by tbock** [comment]
@abbyrrobles @GeoFe33 can we close then?

**Comment by abbyrrobles** [comment]
Done @tbock
