### ISSUE TITLE
Add Table View to 3D Viewer

### ISSUE THREAD

**Issue by tbock** [USEPA/R9-CentralBasin#4]
JS API feature table widget.  https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-FeatureTable.html
@froberts What layers should be used for this?

add gamma data

add TCE and PCE once 2D layers added to map

enable interactive functionality between table and map

**Comment by froberts** [comment]
The primary wells layer and the chemical layer (e.g. PCE) would also be nice to be seen in the table.

**Comment by froberts** [comment]
From Matt M.  Can we get a summary table (like those in other gis applications where the dataset and the cumulative number of elements is shown at the bottom of the map) illustrating # of wells. Key elements are the total number of wells in the Wells 2d and Wells 3d datasets. Priority remains the production wells if we need to choose.
