### ISSUE TITLE
Create summary of all chemicals in both wells and GAMA and send to Matt

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#45]

**Comment by tbock** [comment]
@froberts @GeoFe33 status?

**Comment by GeoFe33** [comment]
Link to List on EPA Sharepoint (user access restricted)

[Sharepoint Link to Completed (and Vote On) Chemical List](https://usepa.sharepoint.com/:x:/r/sites/CENTRALBASIN3DPROJECT/Shared%20Documents/MASTER%20CHEMICAL%20LIST%20BY%20AGENCY%20%20APRIL%2018%202022/20220418_CentralBasin_ChemicalList_PleaseMark4thSheet.xlsx?d=w58e2800e40f84d2cb0735647a2b43947&csf=1&web=1&e=oz4QQ7)
