### ISSUE TITLE
Allow user to pick a chemical from a list and add it to the viewer

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#47]

**Comment by tbock** [comment]
How is this different from issue #96 @abbyrrobles @GeoFe33

**Comment by GeoFe33** [comment]
@froberts Do you have anything to add?

**Comment by MatteoBerg** [comment]
@froberts @tbock is [this](https://developers.arcgis.com/javascript/latest/sample-code/featurefilter-attributes/) a good example of the ask for this issue and #96? 

[filter-features.webm](https://user-images.githubusercontent.com/94854808/200892051-25d1d6e1-aa17-47e6-9d89-32087f878ba6.webm)


Present users with a pick list of chemicals and then apply a filter to that layer?

**Comment by tbock** [comment]
Can you up a select/typeahead/autocomplete input in there instead?  There are a lot to choose from. @MatteoBerg

**Comment by MatteoBerg** [comment]
> Can you up a select/typeahead/autocomplete input in there instead? There are a lot to choose from. @MatteoBerg

Here's how it looks so far, using a calcite combobox which provides typeahead

[filter-features.webm](https://user-images.githubusercontent.com/94854808/201215061-910aadd3-0c46-4154-9e5a-addb5e264198.webm)
