### ISSUE TITLE
Add Help Documentation with Links of How Tos

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#50]
Work with Brad to identify parts of the JS API help docs to show people how to use tools (e.g. slice)

**Comment by bsnider** [comment]
add link to various esri docs for out of the box widgets

**Comment by GeoFe33** [comment]
[CentralBasin3D_HowToUseSceneViewerResources.docx](https://github.com/USEPA/R9-CentralBasin/files/7077876/CentralBasin3D_HowToUseSceneViewerResources.docx)

**Comment by froberts** [comment]
Brad is going to make a place for Lisa to update and place links to youtube videos of help topics.  E.g. how to use the slice tool.

**Comment by GeoFe33** [comment]
Help documentation and videos were developed for the measurement and slice tools.

**Comment by GeoFe33** [comment]
Files for documentation are in shared location.  Still need information on where to place links for the videos (if that's what we still want to do).  If youtube is utilized, then access to an account would be required.

**Comment by tbock** [comment]
@jlherring do we have youtube as option with EPA? otherwise we will have to shove video on ER cloud I guess.

**Comment by jlherring** [comment]
Nope - all EPA youtube is gonna go through a formal public review process. Toss in ER Cloud. Last I heard, all of the existing stuff is old. We prob need to ditch this issue all together until there's something close enough to final to record?

**Comment by kplank1** [comment]
Published this in the application.
