### ISSUE TITLE
Determine why sometimes wells stick out of the ground and trap for it.

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#52]
Email sent to Phil:
Phil, I occasionally (say 25% of the time) have the 3D well data load and it ends up sticking out of the ground maybe 10 meters.  The other 75% of the time the scene loads and everything is below ground where it belongs.  I haven’t updated the data or changed it, so it makes me thing the scene viewer somehow looses it’s mind for the elevation of the base map.  Have you seen this before, and is there anyway to trap for that?

**Comment by froberts** [comment]
![image](https://user-images.githubusercontent.com/86585/118842003-a85caa00-b87d-11eb-99f1-fad710a30d19.png)

**Comment by tbock** [comment]
@froberts @GeoFe33 @bsnider I believe this is already resolved.  Can someone confirm?

**Comment by tbock** [comment]
Closing a likely not an issue in V2 based on using 3d objects with points.
