### ISSUE TITLE
Create Level of Effort for New TOC with picklist of chemicals

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#55]
Deal with the buffer - so hottest sites show up 
Deal with dynamic drawing/opposed to hosted feature classes
Deal with pulling data ranges for chemicals from hosted table
Deal with All of the above working in time slider
Deal with potential load of 100+ Chemicals in future
Deal with results to other Widgets
Deal with showing results in table
Processing data so it is uniform for WRD/GAMA
Deal with potential dynamic coloring
Deal with displaying multiple chemicals
Deal with ability to choose chemical groups (e.g. chlorinated solvents)

https://gamagroundwater.waterboards.ca.gov/gama/gamamap/public/

https://developers.arcgis.com/javascript/latest/visualization/data-driven-styles/smart-mapping/

**Comment by tbock** [comment]
@abbyrrobles @GeoFe33 I think we need to break this down more.  This isn't very helpful at the moment I think

**Comment by tbock** [comment]
@jlherring Is this still needed?

**Comment by jlherring** [comment]
We have an estimated chunk of funding to work under, so no need for a new LOE until we're through that funding. But agree w/ the comment above - are these all still issues we need to resolve? If so @jdlandau123, please make separate issues. If not, let's close
