### ISSUE TITLE
Add PCE layer to be controller by time slider just like TCE layer

### ISSUE THREAD

**Issue by tbock** [USEPA/R9-CentralBasin#6]
https://epa.maps.arcgis.com/home/item.html?id=eed35d1e8e2c40f2b2481b16470c36ca

The layers will just manually be turned on/off via the layer list

**Comment by tbock** [comment]
Is this issue still valid? @bsnider @GeoFe33

**Comment by GeoFe33** [comment]
Looks like the item no longer exists.
