### ISSUE TITLE
Look into Why is “Monitoring Wells 3D” grayed

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#85]

**Comment by GeoFe33** [comment]
Looked into this in the viewer.  It seems that they do appear once you zoom in.  The other 3D layers under "All Wells" do not have constrained visibility ranges.  The Monitoring Wells 3D and Production Wells 3D should not appear until you reach 1:33,000 (1:21,000 for Prod).

**Comment by tbock** [comment]
This still an issue @froberts @GeoFe33

**Comment by GeoFe33** [comment]
This is a scale-dependent layer.  It works just fine.  Users just need to zoom in farther to see it.  Closing this issue.  Reopen if needed later.
