### ISSUE TITLE
SPGIT Group Layers Permission Issue

### ISSUE THREAD

**Issue by GeoFe33** [USEPA/R9-CentralBasin#88]
![image](https://user-images.githubusercontent.com/54416878/166719059-a28d9b93-ae07-4963-9d65-d20c7a0843b9.png)

Layers will not draw within map.

**Comment by tbock** [comment]
@GeoFe33 I didn't get this error on load.  Reopen if needed.

**Comment by GeoFe33** [comment]
I reached out about these and worked with Greg to get them available to us again.
