### ISSUE TITLE
Update Gama data

### ISSUE THREAD

**Issue by GeoFe33** [USEPA/R9-CentralBasin#98]
Frank has asked Matt about getting an update for the data.  So that we have it ready for this year's processing.

**Comment by GeoFe33** [comment]
@froberts was working on the new refresh of data from GAMA and WRD.  I believe we have received it and it needs processing.

**Comment by jlherring** [comment]
@GeoFe33 @abbyrrobles Please break out into relevant issues

**Comment by tbock** [comment]
@abbyrrobles Is this issue relevant anymore/update title? Are we using WRD data at all? Status?

**Comment by abbyrrobles** [comment]
Think we can change this to just update gama data. WRD will not be included. I will change the title.

**Comment by kplank1** [comment]
Aquired required data from website and implemented new python script to imported it
